export interface AnonymousPersona {
  name: string
  avatar: string
  color: string
}

export const ANONYMOUS_PERSONAS: readonly AnonymousPersona[] = [
  { name: 'Anonymous Panda', avatar: '🐼', color: 'emerald' },
  { name: 'Anonymous Ghost', avatar: '👻', color: 'violet' },
  { name: 'Anonymous Penguin', avatar: '🐧', color: 'sky' },
  { name: 'Anonymous Potato', avatar: '🥔', color: 'amber' },
  { name: 'Anonymous Fox', avatar: '🦊', color: 'orange' },
  { name: 'Anonymous Cat', avatar: '🐱', color: 'rose' },
  { name: 'Anonymous Owl', avatar: '🦉', color: 'indigo' },
  { name: 'Anonymous Tiger', avatar: '🐯', color: 'amber' },
  { name: 'Anonymous Otter', avatar: '🦦', color: 'teal' },
  { name: 'Anonymous Raccoon', avatar: '🦝', color: 'zinc' },
  { name: 'Anonymous Koala', avatar: '🐨', color: 'cyan' },
  { name: 'Anonymous Hedgehog', avatar: '🦔', color: 'amber' },
  { name: 'Anonymous Rabbit', avatar: '🐰', color: 'pink' },
  { name: 'Anonymous Bear', avatar: '🐻', color: 'yellow' },
  { name: 'Anonymous Lion', avatar: '🦁', color: 'amber' },
  { name: 'Anonymous Frog', avatar: '🐸', color: 'emerald' },
  { name: 'Anonymous Monkey', avatar: '🐵', color: 'orange' },
  { name: 'Anonymous Duck', avatar: '🦆', color: 'yellow' },
  { name: 'Anonymous Falcon', avatar: '🦅', color: 'sky' },
  { name: 'Anonymous Badger', avatar: '🦡', color: 'zinc' },
  { name: 'Anonymous Beaver', avatar: '🦫', color: 'amber' },
  { name: 'Anonymous Deer', avatar: '🦌', color: 'emerald' },
  { name: 'Anonymous Wolf', avatar: '🐺', color: 'indigo' },
  { name: 'Anonymous Chameleon', avatar: '🦎', color: 'emerald' },
  { name: 'Anonymous Octopus', avatar: '🐙', color: 'violet' },
  { name: 'Anonymous Dolphin', avatar: '🐬', color: 'sky' },
  { name: 'Anonymous Seal', avatar: '🦭', color: 'teal' },
  { name: 'Anonymous Sloth', avatar: '🦥', color: 'amber' },
  { name: 'Anonymous Alpaca', avatar: '🦙', color: 'rose' },
  { name: 'Anonymous Kangaroo', avatar: '🦘', color: 'orange' },
  { name: 'Anonymous Turtle', avatar: '🐢', color: 'emerald' },
  { name: 'Anonymous Squirrel', avatar: '🐿️', color: 'amber' },
  { name: 'Anonymous Zebra', avatar: '🦓', color: 'zinc' },
  { name: 'Anonymous Giraffe', avatar: '🦒', color: 'yellow' },
  { name: 'Anonymous Elephant', avatar: '🐘', color: 'sky' },
  { name: 'Anonymous Hippo', avatar: '🦛', color: 'indigo' },
  { name: 'Anonymous Rhinoceros', avatar: '🦏', color: 'zinc' },
  { name: 'Anonymous Moose', avatar: '🫎', color: 'amber' },
  { name: 'Anonymous Whale', avatar: '🐳', color: 'blue' },
  { name: 'Anonymous Shark', avatar: '🦈', color: 'teal' },
  { name: 'Anonymous Flamingo', avatar: '🦩', color: 'rose' },
  { name: 'Anonymous Parrot', avatar: '🦜', color: 'emerald' },
  { name: 'Anonymous Swan', avatar: '🦢', color: 'zinc' },
  { name: 'Anonymous Cheetah', avatar: '🐆', color: 'amber' },
  { name: 'Anonymous Leopard', avatar: '🐆', color: 'yellow' },
  { name: 'Anonymous Hamster', avatar: '🐹', color: 'amber' },
  { name: 'Anonymous Walrus', avatar: '🦭', color: 'blue' },
  { name: 'Anonymous Capybara', avatar: '🐾', color: 'amber' },
  { name: 'Anonymous Lynx', avatar: '🐱', color: 'indigo' },
  { name: 'Anonymous Quokka', avatar: '🐨', color: 'yellow' },
  { name: 'Anonymous Lemur', avatar: '🐒', color: 'orange' },
  { name: 'Anonymous Dragon', avatar: '🐉', color: 'emerald' },
  { name: 'Anonymous Phoenix', avatar: '🦅', color: 'orange' },
  { name: 'Anonymous Raven', avatar: '🦅', color: 'zinc' },
  { name: 'Anonymous Sparrow', avatar: '🐦', color: 'amber' },
  { name: 'Anonymous Heron', avatar: '🦩', color: 'sky' },
  { name: 'Anonymous Finch', avatar: '🐦', color: 'rose' },
  { name: 'Anonymous Hawk', avatar: '🦅', color: 'amber' },
  { name: 'Anonymous Narwhal', avatar: '🦄', color: 'cyan' },
  { name: 'Anonymous Puffin', avatar: '🐧', color: 'sky' },
] as const
